export const profiles = [
    {
      id: "1",
      name: "Luis Pérez",
      age: 32,
      status: "Ingeniero de Sistemas",
      interestRate: "5%",
      repaymentTime: "12 meses",
      requestedAmount: "S/10,000",
      loanReasonTags: ["Negocio", "Expansión"],
      loanExplanation: "Ampliar mi empresa de tecnología.",
      repaymentJustification: "Ingresos de nuevos contratos.",
      score: 85,
      loanHistory: [
        "Préstamo 1: Pagado",
        "Préstamo 2: Pagado",
        "Préstamo 3: Pendiente",
      ],
      shortDescription: "Apasionado por la innovación y la tecnología.",
      profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
      id: "2",
      name: "María López",
      age: 27,
      status: "Médica General",
      interestRate: "6%",
      repaymentTime: "24 meses",
      requestedAmount: "S/15,000",
      loanReasonTags: ["Educación", "Especialización"],
      loanExplanation: "Curso de especialización en pediatría.",
      repaymentJustification: "Mejor salario tras especialización.",
      score: 90,
      loanHistory: [
        "Préstamo 1: Pagado",
        "Préstamo 2: Pagado",
        "Préstamo 3: Pagado",
      ],
      shortDescription: "Dedicada a mejorar la salud de los niños.",
      profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    {
      id: "3",
      name: "Carlos Ramírez",
      age: 40,
      status: "Maestro de Primaria",
      interestRate: "4.5%",
      repaymentTime: "18 meses",
      requestedAmount: "S/8,000",
      loanReasonTags: ["Hogar"],
      loanExplanation: "Renovación de vivienda.",
      repaymentJustification: "Trabajo estable y ahorros.",
      score: 80,
      loanHistory: [
        "Préstamo 1: Pagado",
        "Préstamo 2: Pendiente",
        "Préstamo 3: Pendiente",
      ],
      shortDescription: "Comprometido con la educación de los niños.",
      profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    {
      id: "4",
      name: "Ana Torres",
      age: 35,
      status: "Arquitecta",
      interestRate: "5.2%",
      repaymentTime: "36 meses",
      requestedAmount: "S/20,000",
      loanReasonTags: ["Negocio", "Diseño"],
      loanExplanation: "Abrir un estudio de diseño arquitectónico.",
      repaymentJustification: "Proyectos en cartera.",
      score: 88,
      loanHistory: ["Préstamo 1: Pagado"],
      shortDescription: "Apasionada por la creatividad y la arquitectura.",
      profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
    },
    {
      id: "5",
      name: "Pedro Castillo",
      age: 45,
      status: "Empresario",
      interestRate: "7%",
      repaymentTime: "48 meses",
      requestedAmount: "S/50,000",
      loanReasonTags: ["Expansión"],
      loanExplanation: "Abrir una nueva sucursal.",
      repaymentJustification: "Ingresos de sucursal principal.",
      score: 92,
      loanHistory: ["Préstamo 1: Pagado", "Préstamo 2: Pagado"],
      shortDescription: "Emprendedor con visiones de crecimiento.",
      profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
    },
    {
      id: "6",
      name: "Sofía Mendoza",
      age: 30,
      status: "Diseñadora Gráfica",
      interestRate: "5.5%",
      repaymentTime: "24 meses",
      requestedAmount: "S/12,000",
      loanReasonTags: ["Negocio", "Equipamiento"],
      loanExplanation: "Compra de equipos de diseño.",
      repaymentJustification: "Clientes asegurados.",
      score: 87,
      loanHistory: ["Préstamo 1: Pagado"],
      shortDescription: "Creatividad y arte en cada proyecto.",
      profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
    },
    {
      id: "7",
      name: "Ricardo Gómez",
      age: 50,
      status: "Contador Público",
      interestRate: "4.8%",
      repaymentTime: "30 meses",
      requestedAmount: "S/18,000",
      loanReasonTags: ["Inversión"],
      loanExplanation: "Compra de software contable.",
      repaymentJustification: "Aumento de clientes.",
      score: 89,
      loanHistory: ["Préstamo 1: Pagado", "Préstamo 2: Pagado"],
      shortDescription: "Precisión y eficiencia financiera.",
      profileImage: "https://randomuser.me/api/portraits/men/7.jpg",
    },
    {
      id: "8",
      name: "Luis Pérez",
      age: 32,
      status: "Ingeniero de Sistemas",
      interestRate: "5%",
      repaymentTime: "12 meses",
      requestedAmount: "S/10,000",
      loanReasonTags: ["Negocio", "Expansión"],
      loanExplanation: "Ampliar mi empresa de tecnología.",
      repaymentJustification: "Ingresos de nuevos contratos.",
      score: 85,
      loanHistory: [
        "Préstamo 1: Pagado",
        "Préstamo 2: Pagado",
        "Préstamo 3: Pendiente",
      ],
      shortDescription: "Apasionado por la innovación y la tecnología.",
      profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
      id: "9",
      name: "María López",
      age: 27,
      status: "Médica General",
      interestRate: "6%",
      repaymentTime: "24 meses",
      requestedAmount: "S/15,000",
      loanReasonTags: ["Educación", "Especialización"],
      loanExplanation: "Curso de especialización en pediatría.",
      repaymentJustification: "Mejor salario tras especialización.",
      score: 90,
      loanHistory: [
        "Préstamo 1: Pagado",
        "Préstamo 2: Pagado",
        "Préstamo 3: Pagado",
      ],
      shortDescription: "Dedicada a mejorar la salud de los niños.",
      profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    {
      id: "10",
      name: "Ana Torres",
      age: 35,
      status: "Arquitecta",
      interestRate: "5.2%",
      repaymentTime: "36 meses",
      requestedAmount: "S/20,000",
      loanReasonTags: ["Negocio", "Diseño"],
      loanExplanation: "Abrir un estudio de diseño arquitectónico.",
      repaymentJustification: "Proyectos en cartera.",
      score: 88,
      loanHistory: ["Préstamo 1: Pagado"],
      shortDescription: "Apasionada por la creatividad y la arquitectura.",
      profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
    },

];


export const messages = [
  {
    id: "m1",
    profileId: "1",
    messages: [
      { sender: "Luis Pérez", text: "Hola, ¿cómo estás?", timestamp: "10:00 AM" },
      { sender: "Tú", text: "¡Hola Luis! Todo bien, ¿y tú?", timestamp: "10:05 AM" },
    ],
  },
  {
    id: "m2",
    profileId: "2",
    messages: [
      { sender: "María López", text: "¿Me podrías dar más detalles?", timestamp: "11:00 AM" },
      { sender: "Tú", text: "Por supuesto, te explico...", timestamp: "11:10 AM" },
    ],
  },
  {
    id: "m3",
    profileId: "3",
    messages: [
      { sender: "Carlos Ramírez", text: "¿Cuándo puedo recibir una respuesta?", timestamp: "12:30 PM" },
      { sender: "Tú", text: "En breve te confirmo.", timestamp: "12:35 PM" },
    ],
  },
  {
    id: "m4",
    profileId: "4",
    messages: [
      { sender: "Ana Torres", text: "Estoy interesada en conocer más sobre las opciones de pago.", timestamp: "2:00 PM" },
      { sender: "Tú", text: "Claro, te comparto los detalles a continuación.", timestamp: "2:05 PM" },
    ],
  },
  {
    id: "m5",
    profileId: "5",
    messages: [
      { sender: "Pedro Castillo", text: "¿Hay algún requisito adicional?", timestamp: "3:45 PM" },
      { sender: "Tú", text: "Déjame verificarlo y te informo.", timestamp: "3:50 PM" },
    ],
  },
  {
    id: "m6",
    profileId: "6",
    messages: [
      { sender: "Sofía Mendoza", text: "Quisiera saber si es posible ajustar el monto del préstamo.", timestamp: "4:20 PM" },
      { sender: "Tú", text: "Podemos analizarlo y ver qué opciones hay.", timestamp: "4:25 PM" },
    ],
  },
  {
    id: "m7",
    profileId: "7",
    messages: [
      { sender: "Ricardo Gómez", text: "Necesito información sobre los plazos de pago.", timestamp: "5:10 PM" },
      { sender: "Tú", text: "Aquí tienes los detalles de los plazos.", timestamp: "5:15 PM" },
    ],
  },
  {
    id: "m8",
    profileId: "8",
    messages: [
      { sender: "Luis Pérez", text: "¿Cómo puedo iniciar el proceso de solicitud?", timestamp: "6:00 PM" },
      { sender: "Tú", text: "Te guiaré paso a paso.", timestamp: "6:05 PM" },
    ],
  },
  {
    id: "m9",
    profileId: "9",
    messages: [
      { sender: "María López", text: "¿Cuánto tiempo toma la aprobación?", timestamp: "7:30 PM" },
      { sender: "Tú", text: "Generalmente entre 24 y 48 horas.", timestamp: "7:35 PM" },
    ],
  },
  {
    id: "m10",
    profileId: "10",
    messages: [
      { sender: "Ana Torres", text: "Estoy lista para proceder con la solicitud.", timestamp: "8:00 PM" },
      { sender: "Tú", text: "¡Perfecto! Te enviaré los siguientes pasos.", timestamp: "8:05 PM" },
    ],
  },
];
